spring:
  application:
    name: kafka-example
  kafka:
    bootstrapServers: http://localhost:9092
    consumer:
      enable-auto-commit: false  # Disable auto-commit to handle commit manually
      topicName: test-topic
      isolation-level: read_committed  # Ensures only committed messages are read
      groupId: test-madhu-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      enable-idempotence: true  # Ensure producer idempotence
      acks: all  # Ensure all in-sync replicas acknowledge the message
      retries: 5  # Retrying indefinitely on failure
      max-in-flight-requests-per-connection: 5  # Prevent reordering of messages